<?php 
   /**
    * 												
    *  Tarif au-delà de 20kg uniquement pour les bureaux de poste.												
    *  L'accès à ces tarifs est subordonné à la signature d'un contrat;Vous devez mettre à jour ce tableau en fonction de votre contrat											
    */
   return [
      'france' => [
         0 => [
            'POIDS' => 0.25,
            'SANS SIGNATURE' => 5.5,
            'AVEC SIGNATURE' => 6.47,
            'RETOUR' => 5.5,
            'RETRAIT' => 4.47,
         ],
         1 => [
            'POIDS' => 0.5,
            'SANS SIGNATURE' => 6.2,
            'AVEC SIGNATURE' => 7.17,
            'RETOUR' => 6.2,
            'RETRAIT' => 5.19,
         ],
         2 => [
            'POIDS' => 0.75,
            'SANS SIGNATURE' => 6.93,
            'AVEC SIGNATURE' => 7.9,
            'RETOUR' => 6.93,
            'RETRAIT' => 5.94,
         ],
         3 => [
            'POIDS' => 1.0,
            'SANS SIGNATURE' => 7.52,
            'AVEC SIGNATURE' => 8.49,
            'RETOUR' => 7.52,
            'RETRAIT' => 6.55,
         ],
         4 => [
            'POIDS' => 2.0,
            'SANS SIGNATURE' => 8.34,
            'AVEC SIGNATURE' => 9.31,
            'RETOUR' => 8.34,
            'RETRAIT' => 7.4,
         ],
         5 => [
            'POIDS' => 3.0,
            'SANS SIGNATURE' => 9.16,
            'AVEC SIGNATURE' => 10.13,
            'RETOUR' => 9.16,
            'RETRAIT' => 8.24,
         ],
         6 => [
            'POIDS' => 4.0,
            'SANS SIGNATURE' => 9.98,
            'AVEC SIGNATURE' => 10.95,
            'RETOUR' => 9.98,
            'RETRAIT' => 9.09,
         ],
         7 => [
            'POIDS' => 5.0,
            'SANS SIGNATURE' => 10.8,
            'AVEC SIGNATURE' => 11.77,
            'RETOUR' => 10.8,
            'RETRAIT' => 9.93,
         ],
         8 => [
            'POIDS' => 6.0,
            'SANS SIGNATURE' => 11.63,
            'AVEC SIGNATURE' => 12.6,
            'RETOUR' => 11.63,
            'RETRAIT' => 10.79,
         ],
         9 => [
            'POIDS' => 7.0,
            'SANS SIGNATURE' => 12.45,
            'AVEC SIGNATURE' => 13.42,
            'RETOUR' => 12.45,
            'RETRAIT' => 11.63,
         ],
         10 => [
            'POIDS' => 8.0,
            'SANS SIGNATURE' => 13.25,
            'AVEC SIGNATURE' => 14.22,
            'RETOUR' => 13.25,
            'RETRAIT' => 12.46,
         ],
         11 => [
            'POIDS' => 9.0,
            'SANS SIGNATURE' => 14.08,
            'AVEC SIGNATURE' => 15.05,
            'RETOUR' => 14.08,
            'RETRAIT' => 13.32,
         ],
         12 => [
            'POIDS' => 10.0,
            'SANS SIGNATURE' => 14.91,
            'AVEC SIGNATURE' => 15.88,
            'RETOUR' => 14.91,
            'RETRAIT' => 14.17,
         ],
         13 => [
            'POIDS' => 11.0,
            'SANS SIGNATURE' => 15.73,
            'AVEC SIGNATURE' => 16.7,
            'RETOUR' => 15.73,
            'RETRAIT' => 15.02,
         ],
         14 => [
            'POIDS' => 12.0,
            'SANS SIGNATURE' => 16.55,
            'AVEC SIGNATURE' => 17.52,
            'RETOUR' => 16.55,
            'RETRAIT' => 15.86,
         ],
         15 => [
            'POIDS' => 13.0,
            'SANS SIGNATURE' => 17.36,
            'AVEC SIGNATURE' => 18.33,
            'RETOUR' => 17.36,
            'RETRAIT' => 16.7,
         ],
         16 => [
            'POIDS' => 14.0,
            'SANS SIGNATURE' => 18.2,
            'AVEC SIGNATURE' => 19.17,
            'RETOUR' => 18.2,
            'RETRAIT' => 17.56,
         ],
         17 => [
            'POIDS' => 15.0,
            'SANS SIGNATURE' => 19.01,
            'AVEC SIGNATURE' => 19.98,
            'RETOUR' => 19.01,
            'RETRAIT' => 18.4,
         ],
         18 => [
            'POIDS' => 16.0,
            'SANS SIGNATURE' => 19.84,
            'AVEC SIGNATURE' => 20.81,
            'RETOUR' => 19.84,
            'RETRAIT' => 19.25,
         ],
         19 => [
            'POIDS' => 17.0,
            'SANS SIGNATURE' => 20.65,
            'AVEC SIGNATURE' => 21.62,
            'RETOUR' => 20.65,
            'RETRAIT' => 20.09,
         ],
         20 => [
            'POIDS' => 18.0,
            'SANS SIGNATURE' => 21.47,
            'AVEC SIGNATURE' => 22.44,
            'RETOUR' => 21.47,
            'RETRAIT' => 20.93,
         ],
         21 => [
            'POIDS' => 19.0,
            'SANS SIGNATURE' => 22.3,
            'AVEC SIGNATURE' => 23.27,
            'RETOUR' => 22.3,
            'RETRAIT' => 21.79,
         ],
         22 => [
            'POIDS' => 20.0,
            'SANS SIGNATURE' => 23.11,
            'AVEC SIGNATURE' => 24.08,
            'RETOUR' => 23.11,
            'RETRAIT' => 22.62,
         ],
         23 => [
            'POIDS' => 21.0,
            'SANS SIGNATURE' => 23.94,
            'AVEC SIGNATURE' => 24.91,
            'RETOUR' => 23.94,
            'RETRAIT' => 23.48,
         ],
         24 => [
            'POIDS' => 22.0,
            'SANS SIGNATURE' => 24.75,
            'AVEC SIGNATURE' => 25.72,
            'RETOUR' => 24.75,
            'RETRAIT' => 24.32,
         ],
         25 => [
            'POIDS' => 23.0,
            'SANS SIGNATURE' => 25.58,
            'AVEC SIGNATURE' => 26.55,
            'RETOUR' => 25.58,
            'RETRAIT' => 25.17,
         ],
         26 => [
            'POIDS' => 24.0,
            'SANS SIGNATURE' => 26.4,
            'AVEC SIGNATURE' => 27.37,
            'RETOUR' => 26.4,
            'RETRAIT' => 26.02,
         ],
         27 => [
            'POIDS' => 25.0,
            'SANS SIGNATURE' => 27.21,
            'AVEC SIGNATURE' => 28.18,
            'RETOUR' => 27.21,
            'RETRAIT' => 26.85,
         ],
         28 => [
            'POIDS' => 26.0,
            'SANS SIGNATURE' => 28.04,
            'AVEC SIGNATURE' => 29.01,
            'RETOUR' => 28.04,
            'RETRAIT' => 27.71,
         ],
         29 => [
            'POIDS' => 27.0,
            'SANS SIGNATURE' => 28.86,
            'AVEC SIGNATURE' => 29.83,
            'RETOUR' => 28.86,
            'RETRAIT' => 28.55,
         ],
         30 => [
            'POIDS' => 28.0,
            'SANS SIGNATURE' => 29.68,
            'AVEC SIGNATURE' => 30.65,
            'RETOUR' => 29.68,
            'RETRAIT' => 29.4,
         ],
         31 => [
            'POIDS' => 29.0,
            'SANS SIGNATURE' => 30.52,
            'AVEC SIGNATURE' => 31.49,
            'RETOUR' => 30.52,
            'RETRAIT' => 30.26,
         ],
         32 => [
            'POIDS' => 30.0,
            'SANS SIGNATURE' => 31.31,
            'AVEC SIGNATURE' => 32.28,
            'RETOUR' => 31.31,
            'RETRAIT' => 31.08,
         ],
      ],
      'outremer' => [
         0 => [
            'POIDS' => 0.5,
            'SANS SIGNATURE OM1' => 9.25,
            'SANS SIGNATURE OM2' => 11.0,
            'AVEC SIGNATURE OM1' => 12.63,
            'AVEC SIGNATURE OM2' => 18.54,
            'RETOUR' => 9.25,
         ],
         1 => [
            'POIDS' => 1.0,
            'SANS SIGNATURE OM1' => 14.04,
            'SANS SIGNATURE OM2' => 17.08,
            'AVEC SIGNATURE OM1' => 16.2,
            'AVEC SIGNATURE OM2' => 22.93,
            'RETOUR' => 14.04,
         ],
         2 => [
            'POIDS' => 2.0,
            'SANS SIGNATURE OM1' => 19.13,
            'SANS SIGNATURE OM2' => 30.35,
            'AVEC SIGNATURE OM1' => 21.83,
            'AVEC SIGNATURE OM2' => 35.68,
            'RETOUR' => 19.13,
         ],
         3 => [
            'POIDS' => 3.0,
            'SANS SIGNATURE OM1' => 24.23,
            'SANS SIGNATURE OM2' => 43.62,
            'AVEC SIGNATURE OM1' => 27.48,
            'AVEC SIGNATURE OM2' => 50.24,
            'RETOUR' => 24.23,
         ],
         4 => [
            'POIDS' => 4.0,
            'SANS SIGNATURE OM1' => 29.33,
            'SANS SIGNATURE OM2' => 54.42,
            'AVEC SIGNATURE OM1' => 31.93,
            'AVEC SIGNATURE OM2' => 60.69,
            'RETOUR' => 29.33,
         ],
         5 => [
            'POIDS' => 5.0,
            'SANS SIGNATURE OM1' => 32.92,
            'SANS SIGNATURE OM2' => 67.11,
            'AVEC SIGNATURE OM1' => 37.06,
            'AVEC SIGNATURE OM2' => 73.33,
            'RETOUR' => 32.92,
         ],
         6 => [
            'POIDS' => 6.0,
            'SANS SIGNATURE OM1' => 39.54,
            'SANS SIGNATURE OM2' => 83.46,
            'AVEC SIGNATURE OM1' => 44.41,
            'AVEC SIGNATURE OM2' => 89.91,
            'RETOUR' => 39.54,
         ],
         7 => [
            'POIDS' => 7.0,
            'SANS SIGNATURE OM1' => 44.62,
            'SANS SIGNATURE OM2' => 96.73,
            'AVEC SIGNATURE OM1' => 50.05,
            'AVEC SIGNATURE OM2' => 101.2,
            'RETOUR' => 44.62,
         ],
         8 => [
            'POIDS' => 8.0,
            'SANS SIGNATURE OM1' => 48.59,
            'SANS SIGNATURE OM2' => 107.09,
            'AVEC SIGNATURE OM1' => 53.25,
            'AVEC SIGNATURE OM2' => 111.27,
            'RETOUR' => 48.59,
         ],
         9 => [
            'POIDS' => 9.0,
            'SANS SIGNATURE OM1' => 53.43,
            'SANS SIGNATURE OM2' => 117.9,
            'AVEC SIGNATURE OM1' => 58.65,
            'AVEC SIGNATURE OM2' => 123.92,
            'RETOUR' => 53.43,
         ],
         10 => [
            'POIDS' => 10.0,
            'SANS SIGNATURE OM1' => 59.23,
            'SANS SIGNATURE OM2' => 130.59,
            'AVEC SIGNATURE OM1' => 64.05,
            'AVEC SIGNATURE OM2' => 136.56,
            'RETOUR' => 59.23,
         ],
         11 => [
            'POIDS' => 15.0,
            'SANS SIGNATURE OM1' => 84.73,
            'SANS SIGNATURE OM2' => 203.74,
            'AVEC SIGNATURE OM1' => 92.94,
            'AVEC SIGNATURE OM2' => 209.98,
            'RETOUR' => 84.73,
         ],
         12 => [
            'POIDS' => 20.0,
            'SANS SIGNATURE OM1' => 109.03,
            'SANS SIGNATURE OM2' => 259.08,
            'AVEC SIGNATURE OM1' => 115.87,
            'AVEC SIGNATURE OM2' => 265.05,
            'RETOUR' => 109.03,
         ],
         13 => [
            'POIDS' => 25.0,
            'SANS SIGNATURE OM1' => 137.75,
            'SANS SIGNATURE OM2' => 323.33,
            'AVEC SIGNATURE OM1' => 142.86,
            'AVEC SIGNATURE OM2' => 329.3,
            'RETOUR' => 137.75,
         ],
         14 => [
            'POIDS' => 30.0,
            'SANS SIGNATURE OM1' => 166.46,
            'SANS SIGNATURE OM2' => 387.56,
            'AVEC SIGNATURE OM1' => 169.83,
            'AVEC SIGNATURE OM2' => 393.53,
            'RETOUR' => 166.46,
         ],
      ],
      'internationale' => [
         0 => [
            'POIDS' => 0.5,
            'EXPERT ET RETOUR ZONE1' => 10.49,
            'EXPERT ET RETOUR ZONE2' => 11.73,
            'EXPERT ET RETOUR ZONE3' => 11.78,
            'EXPERT ET RETOUR ZONE4' => 14.45,
            'EXPERT ET RETOUR ZONE5' => 22.08,
            'EXPERT ET RETOUR ZONE6' => 25.32,
         ],
         1 => [
            'POIDS' => 1.0,
            'EXPERT ET RETOUR ZONE1' => 12.33,
            'EXPERT ET RETOUR ZONE2' => 14.36,
            'EXPERT ET RETOUR ZONE3' => 14.4,
            'EXPERT ET RETOUR ZONE4' => 17.2,
            'EXPERT ET RETOUR ZONE5' => 24.42,
            'EXPERT ET RETOUR ZONE6' => 29.79,
         ],
         2 => [
            'POIDS' => 2.0,
            'EXPERT ET RETOUR ZONE1' => 13.07,
            'EXPERT ET RETOUR ZONE2' => 15.81,
            'EXPERT ET RETOUR ZONE3' => 15.98,
            'EXPERT ET RETOUR ZONE4' => 18.7,
            'EXPERT ET RETOUR ZONE5' => 33.48,
            'EXPERT ET RETOUR ZONE6' => 40.9,
         ],
         3 => [
            'POIDS' => 3.0,
            'EXPERT ET RETOUR ZONE1' => 13.87,
            'EXPERT ET RETOUR ZONE2' => 16.71,
            'EXPERT ET RETOUR ZONE3' => 17.32,
            'EXPERT ET RETOUR ZONE4' => 20.32,
            'EXPERT ET RETOUR ZONE5' => 42.53,
            'EXPERT ET RETOUR ZONE6' => 52.24,
         ],
         4 => [
            'POIDS' => 4.0,
            'EXPERT ET RETOUR ZONE1' => 14.64,
            'EXPERT ET RETOUR ZONE2' => 17.49,
            'EXPERT ET RETOUR ZONE3' => 18.96,
            'EXPERT ET RETOUR ZONE4' => 22.48,
            'EXPERT ET RETOUR ZONE5' => 48.74,
            'EXPERT ET RETOUR ZONE6' => 63.35,
         ],
         5 => [
            'POIDS' => 5.0,
            'EXPERT ET RETOUR ZONE1' => 15.39,
            'EXPERT ET RETOUR ZONE2' => 18.34,
            'EXPERT ET RETOUR ZONE3' => 20.63,
            'EXPERT ET RETOUR ZONE4' => 26.74,
            'EXPERT ET RETOUR ZONE5' => 52.03,
            'EXPERT ET RETOUR ZONE6' => 72.84,
         ],
         6 => [
            'POIDS' => 6.0,
            'EXPERT ET RETOUR ZONE1' => 16.13,
            'EXPERT ET RETOUR ZONE2' => 19.13,
            'EXPERT ET RETOUR ZONE3' => 26.84,
            'EXPERT ET RETOUR ZONE4' => 30.0,
            'EXPERT ET RETOUR ZONE5' => 66.51,
            'EXPERT ET RETOUR ZONE6' => 83.68,
         ],
         7 => [
            'POIDS' => 7.0,
            'EXPERT ET RETOUR ZONE1' => 16.86,
            'EXPERT ET RETOUR ZONE2' => 20.03,
            'EXPERT ET RETOUR ZONE3' => 28.3,
            'EXPERT ET RETOUR ZONE4' => 33.88,
            'EXPERT ET RETOUR ZONE5' => 77.0,
            'EXPERT ET RETOUR ZONE6' => 94.62,
         ],
         8 => [
            'POIDS' => 8.0,
            'EXPERT ET RETOUR ZONE1' => 17.6,
            'EXPERT ET RETOUR ZONE2' => 20.82,
            'EXPERT ET RETOUR ZONE3' => 29.66,
            'EXPERT ET RETOUR ZONE4' => 38.6,
            'EXPERT ET RETOUR ZONE5' => 85.31,
            'EXPERT ET RETOUR ZONE6' => 105.47,
         ],
         9 => [
            'POIDS' => 9.0,
            'EXPERT ET RETOUR ZONE1' => 18.34,
            'EXPERT ET RETOUR ZONE2' => 21.6,
            'EXPERT ET RETOUR ZONE3' => 31.05,
            'EXPERT ET RETOUR ZONE4' => 41.33,
            'EXPERT ET RETOUR ZONE5' => 88.9,
            'EXPERT ET RETOUR ZONE6' => 116.57,
         ],
         10 => [
            'POIDS' => 10.0,
            'EXPERT ET RETOUR ZONE1' => 19.08,
            'EXPERT ET RETOUR ZONE2' => 22.4,
            'EXPERT ET RETOUR ZONE3' => 32.4,
            'EXPERT ET RETOUR ZONE4' => 44.68,
            'EXPERT ET RETOUR ZONE5' => 93.34,
            'EXPERT ET RETOUR ZONE6' => 127.42,
         ],
         11 => [
            'POIDS' => 15.0,
            'EXPERT ET RETOUR ZONE1' => 23.29,
            'EXPERT ET RETOUR ZONE2' => 26.77,
            'EXPERT ET RETOUR ZONE3' => 40.16,
            'EXPERT ET RETOUR ZONE4' => 59.68,
            'EXPERT ET RETOUR ZONE5' => 136.66,
            'EXPERT ET RETOUR ZONE6' => 176.55,
         ],
         12 => [
            'POIDS' => 20.0,
            'EXPERT ET RETOUR ZONE1' => 27.51,
            'EXPERT ET RETOUR ZONE2' => 31.05,
            'EXPERT ET RETOUR ZONE3' => 47.81,
            'EXPERT ET RETOUR ZONE4' => 69.64,
            'EXPERT ET RETOUR ZONE5' => 149.67,
            'EXPERT ET RETOUR ZONE6' => 226.75,
         ],
         13 => [
            'POIDS' => 25.0,
            'EXPERT ET RETOUR ZONE1' => 31.72,
            'EXPERT ET RETOUR ZONE2' => 35.31,
            'EXPERT ET RETOUR ZONE3' => 55.48,
            'EXPERT ET RETOUR ZONE4' => 82.11,
            'EXPERT ET RETOUR ZONE5' => 192.12,
            'EXPERT ET RETOUR ZONE6' => 275.88,
         ],
         14 => [
            'POIDS' => 30.0,
            'EXPERT ET RETOUR ZONE1' => 35.93,
            'EXPERT ET RETOUR ZONE2' => 39.58,
            'EXPERT ET RETOUR ZONE3' => 57.69,
            'EXPERT ET RETOUR ZONE4' => 94.92,
            'EXPERT ET RETOUR ZONE5' => 221.41,
            'EXPERT ET RETOUR ZONE6' => 325.01,
         ],
      ],
      'europe' => [
         0 => [
            'POIDS' => 0.5,
            'SANS SIGNATURE ZONE1' => 7.85,
            'SANS SIGNATURE ZONE3' => 10.19,
            'AVEC SIGNATURE ZONE1' => 8.37,
            'AVEC SIGNATURE ZONE2' => 9.61,
            'AVEC SIGNATURE ZONE3' => 10.71,
            'AVEC SIGNATURE ZONE4' => 12.31,
            'RETRAIT ZONE1' => 7.85,
            'RETRAIT ZONE2' => 9.09,
            'RETRAIT ZONE3' => 10.19,
            'RETRAIT ZONE4' => 11.79,
         ],
         1 => [
            'POIDS' => 1.0,
            'SANS SIGNATURE ZONE1' => 9.68,
            'SANS SIGNATURE ZONE3' => 12.79,
            'AVEC SIGNATURE ZONE1' => 10.21,
            'AVEC SIGNATURE ZONE2' => 12.22,
            'AVEC SIGNATURE ZONE3' => 13.31,
            'AVEC SIGNATURE ZONE4' => 15.06,
            'RETRAIT ZONE1' => 9.68,
            'RETRAIT ZONE2' => 11.7,
            'RETRAIT ZONE3' => 12.79,
            'RETRAIT ZONE4' => 14.53,
         ],
         2 => [
            'POIDS' => 2.0,
            'SANS SIGNATURE ZONE1' => 10.41,
            'SANS SIGNATURE ZONE3' => 14.36,
            'AVEC SIGNATURE ZONE1' => 10.93,
            'AVEC SIGNATURE ZONE2' => 13.67,
            'AVEC SIGNATURE ZONE3' => 14.88,
            'AVEC SIGNATURE ZONE4' => 16.57,
            'RETRAIT ZONE1' => 10.41,
            'RETRAIT ZONE2' => 13.16,
            'RETRAIT ZONE3' => 14.36,
            'RETRAIT ZONE4' => 16.04,
         ],
         3 => [
            'POIDS' => 3.0,
            'SANS SIGNATURE ZONE1' => 11.21,
            'SANS SIGNATURE ZONE3' => 15.7,
            'AVEC SIGNATURE ZONE1' => 11.73,
            'AVEC SIGNATURE ZONE2' => 14.56,
            'AVEC SIGNATURE ZONE3' => 16.22,
            'AVEC SIGNATURE ZONE4' => 18.17,
            'RETRAIT ZONE1' => 11.21,
            'RETRAIT ZONE2' => 14.04,
            'RETRAIT ZONE3' => 15.7,
            'RETRAIT ZONE4' => 17.64,
         ],
         4 => [
            'POIDS' => 4.0,
            'SANS SIGNATURE ZONE1' => 11.99,
            'SANS SIGNATURE ZONE3' => 17.33,
            'AVEC SIGNATURE ZONE1' => 12.52,
            'AVEC SIGNATURE ZONE2' => 15.36,
            'AVEC SIGNATURE ZONE3' => 17.86,
            'AVEC SIGNATURE ZONE4' => 20.33,
            'RETRAIT ZONE1' => 11.99,
            'RETRAIT ZONE2' => 14.83,
            'RETRAIT ZONE3' => 17.33,
            'RETRAIT ZONE4' => 19.8,
         ],
         5 => [
            'POIDS' => 5.0,
            'SANS SIGNATURE ZONE1' => 12.73,
            'SANS SIGNATURE ZONE3' => 19.0,
            'AVEC SIGNATURE ZONE1' => 13.25,
            'AVEC SIGNATURE ZONE2' => 16.19,
            'AVEC SIGNATURE ZONE3' => 19.52,
            'AVEC SIGNATURE ZONE4' => 24.58,
            'RETRAIT ZONE1' => 12.73,
            'RETRAIT ZONE2' => 15.67,
            'RETRAIT ZONE3' => 19.0,
            'RETRAIT ZONE4' => 24.05,
         ],
         6 => [
            'POIDS' => 6.0,
            'SANS SIGNATURE ZONE1' => 13.46,
            'SANS SIGNATURE ZONE3' => 25.18,
            'AVEC SIGNATURE ZONE1' => 13.99,
            'AVEC SIGNATURE ZONE2' => 16.98,
            'AVEC SIGNATURE ZONE3' => 25.71,
            'AVEC SIGNATURE ZONE4' => 27.81,
            'RETRAIT ZONE1' => 13.46,
            'RETRAIT ZONE2' => 16.47,
            'RETRAIT ZONE3' => 25.18,
            'RETRAIT ZONE4' => 27.29,
         ],
         7 => [
            'POIDS' => 7.0,
            'SANS SIGNATURE ZONE1' => 14.2,
            'SANS SIGNATURE ZONE3' => 26.64,
            'AVEC SIGNATURE ZONE1' => 14.72,
            'AVEC SIGNATURE ZONE2' => 17.88,
            'AVEC SIGNATURE ZONE3' => 27.17,
            'AVEC SIGNATURE ZONE4' => 31.68,
            'RETRAIT ZONE1' => 14.2,
            'RETRAIT ZONE2' => 17.35,
            'RETRAIT ZONE3' => 26.64,
            'RETRAIT ZONE4' => 31.16,
         ],
         8 => [
            'POIDS' => 8.0,
            'SANS SIGNATURE ZONE1' => 14.93,
            'SANS SIGNATURE ZONE3' => 28.01,
            'AVEC SIGNATURE ZONE1' => 15.46,
            'AVEC SIGNATURE ZONE2' => 18.66,
            'AVEC SIGNATURE ZONE3' => 28.54,
            'AVEC SIGNATURE ZONE4' => 36.39,
            'RETRAIT ZONE1' => 14.93,
            'RETRAIT ZONE2' => 18.14,
            'RETRAIT ZONE3' => 28.01,
            'RETRAIT ZONE4' => 35.86,
         ],
         9 => [
            'POIDS' => 9.0,
            'SANS SIGNATURE ZONE1' => 15.67,
            'SANS SIGNATURE ZONE3' => 29.38,
            'AVEC SIGNATURE ZONE1' => 16.19,
            'AVEC SIGNATURE ZONE2' => 19.45,
            'AVEC SIGNATURE ZONE3' => 29.91,
            'AVEC SIGNATURE ZONE4' => 39.11,
            'RETRAIT ZONE1' => 15.67,
            'RETRAIT ZONE2' => 18.92,
            'RETRAIT ZONE3' => 29.38,
            'RETRAIT ZONE4' => 38.59,
         ],
         10 => [
            'POIDS' => 10.0,
            'SANS SIGNATURE ZONE1' => 16.41,
            'SANS SIGNATURE ZONE3' => 30.74,
            'AVEC SIGNATURE ZONE1' => 16.93,
            'AVEC SIGNATURE ZONE2' => 20.24,
            'AVEC SIGNATURE ZONE3' => 31.26,
            'AVEC SIGNATURE ZONE4' => 42.45,
            'RETRAIT ZONE1' => 16.41,
            'RETRAIT ZONE2' => 19.72,
            'RETRAIT ZONE3' => 30.74,
            'RETRAIT ZONE4' => 41.93,
         ],
         11 => [
            'POIDS' => 15.0,
            'SANS SIGNATURE ZONE1' => 20.61,
            'SANS SIGNATURE ZONE3' => 38.47,
            'AVEC SIGNATURE ZONE1' => 21.13,
            'AVEC SIGNATURE ZONE2' => 24.61,
            'AVEC SIGNATURE ZONE3' => 39.0,
            'AVEC SIGNATURE ZONE4' => 57.41,
            'RETRAIT ZONE1' => 20.61,
            'RETRAIT ZONE2' => 24.08,
            'RETRAIT ZONE3' => 38.47,
            'RETRAIT ZONE4' => 56.89,
         ],
         12 => [
            'POIDS' => 20.0,
            'SANS SIGNATURE ZONE1' => 24.81,
            'SANS SIGNATURE ZONE3' => 46.09,
            'AVEC SIGNATURE ZONE1' => 25.33,
            'AVEC SIGNATURE ZONE2' => 28.86,
            'AVEC SIGNATURE ZONE3' => 46.62,
            'AVEC SIGNATURE ZONE4' => 67.35,
            'RETRAIT ZONE1' => 24.81,
            'RETRAIT ZONE2' => 28.34,
            'RETRAIT ZONE3' => 46.09,
            'RETRAIT ZONE4' => 66.82,
         ],
         13 => [
            'POIDS' => 25.0,
            'SANS SIGNATURE ZONE1' => 29.01,
            'SANS SIGNATURE ZONE3' => 53.75,
            'AVEC SIGNATURE ZONE1' => 29.54,
            'AVEC SIGNATURE ZONE2' => 33.11,
            'AVEC SIGNATURE ZONE3' => 54.28,
            'AVEC SIGNATURE ZONE4' => 79.78,
            'RETRAIT ZONE1' => '-',
            'RETRAIT ZONE2' => '-',
            'RETRAIT ZONE3' => '-',
            'RETRAIT ZONE4' => '-',
         ],
         14 => [
            'POIDS' => 30.0,
            'SANS SIGNATURE ZONE1' => 33.22,
            'SANS SIGNATURE ZONE3' => 55.94,
            'AVEC SIGNATURE ZONE1' => 33.75,
            'AVEC SIGNATURE ZONE2' => 37.38,
            'AVEC SIGNATURE ZONE3' => 56.46,
            'AVEC SIGNATURE ZONE4' => 92.55,
            'RETRAIT ZONE1' => '-',
            'RETRAIT ZONE2' => '-',
            'RETRAIT ZONE3' => '-',
            'RETRAIT ZONE4' => '-',
         ],
      ]  
   ];